-- AlterTable
ALTER TABLE `Payrun` ADD COLUMN `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    ADD COLUMN `joursTravailles` INTEGER NULL,
    ADD COLUMN `typeContrat` ENUM('JOURNALIER', 'MENSUELLE', 'HEBDOMADAIRE') NULL;
